# Generated by Django 3.2.5 on 2021-07-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todoitems',
        ),
    ]
